### ISSUE TITLE
connected graph

### ISSUE THREAD

**Issue by wOvOpy** [yolandalalala/GNNInterpreter#2]
hi!
I runned the code, but I found interpretation graphs are not connected graphs in most cases.

**Comment by yolandalalala** [comment]
Hi, if that is the case, you may want to set a higher weight for this regularization term: `dict(key="theta_pairs", criterion=KLDivergencePenalty(binary=True), weight=0)`.

**Comment by wOvOpy** [comment]
ok，I will try it, thanks.
发自我的 iPhone

> 在 2023年11月23日，下午9:10，Xiaoqi Wang ***@***.***> 写道：
> 
> Hi, if that is the case, you may want to set a higher weight for this regularization term
